### ISSUE TITLE
=sys-apps/liquidctl-1.7.0 now requires dev-python/colorlog

### ISSUE THREAD

**Issue by myszkin81** [Tatsh/tatsh-overlay#101]
If no dev-python/colorlog is present on the system then `liquidctl` results in:

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/liquidctl", line 33, in <module>
    sys.exit(load_entry_point('liquidctl==1.7.0', 'console_scripts', 'liquidctl')())
  File "/usr/lib/python-exec/python3.9/liquidctl", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/liquidctl/cli.py", line 77, in <module>
    import colorlog
ModuleNotFoundError: No module named 'colorlog'
```

**Comment by Tatsh** [comment]
Thanks. About to push.
