### ISSUE TITLE
livecheck: GitHub tag check should use pagination

### ISSUE THREAD

**Issue by Tatsh** [Tatsh/tatsh-overlay#129]
```
DEBUG - Parsed path: /mborgerson/xemu/archive/xemu-v0.6.2.tar.gz
DEBUG - Fetching https://github.com/mborgerson/xemu/tags
DEBUG - Adjusting RE for semantic versioning
DEBUG - Using RE: "archive/refs/tags/xemu-v(\d+\.\d+(?:\.\d+)?)\.tar\.gz"
Exception while checking games-emulation/xemu
Traceback (most recent call last):
  File "/var/db/repos/tatsh/./scripts/livecheck.py", line 541, in <module>
    sys.exit(main())
  File "/var/db/repos/tatsh/./scripts/livecheck.py", line 536, in main
    raise e
  File "/var/db/repos/tatsh/./scripts/livecheck.py", line 459, in main
    top_hash = (list(
IndexError: list index out of range
```

Xemu's first tag of the `v*` format is on the second page. Paginate until the first found match up to 10 pages.

**Comment by Tatsh** [comment]
Solution is to use `api.github.com/refs/x/y/tags?per_page=100` for the URL with a custom regex.
