### ISSUE TITLE
dev-python/numba broken

### ISSUE THREAD

**Issue by Tatsh** [Tatsh/tatsh-overlay#158]
Likely caused by `-Wl,--as-needed`.

[As-needed](https://wiki.gentoo.org/wiki/Project:Quality_Assurance/As-needed#Failure_in_execution.2C_undefined_symbols)

```python console
Python 3.10.8 (main, Oct 16 2022, 10:31:19) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(ins)>>> from numba import _dispatcher
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/numba/__init__.py", line 38, in <module>
    from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
  File "/usr/lib/python3.10/site-packages/numba/core/decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "/usr/lib/python3.10/site-packages/numba/stencils/stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "/usr/lib/python3.10/site-packages/numba/core/registry.py", line 4, in <module>
    from numba.core import utils, typing, dispatcher, cpu
  File "/usr/lib/python3.10/site-packages/numba/core/dispatcher.py", line 12, in <module>
    from numba import _dispatcher
ImportError: /usr/lib/python3.10/site-packages/numba/_dispatcher.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK11TypeManager14selectOverloadEPKiS1_Riiibb
```

**Comment by Tatsh** [comment]
For now the workaround is applied. Will reopen if this comes back.
